apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'prod'
spec:
  destination:
    namespace: 'prod'
    server: 'https://kubernetes.default.svc'
  source:
    path: './environment-promotion/env/prod'
    repoURL: 'https://github.com/EsterSteinberger/gitops-cert-level-2-examples.git'
    targetRevision: HEAD
  project: 'default'
