apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'qa'
spec:
  destination:
    namespace: 'qa'
    server: 'https://kubernetes.default.svc'
  source:
    path: './environment-promotion/env/qa'
    repoURL: 'https://github.com/EsterSteinberger/gitops-cert-level-2-examples.git'
    targetRevision: HEAD
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
